// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 5
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){


var __awct;(function(){var a=!1,b=[],c=function(a){var b=n("google_trackConversion"),c=a.gtm_onFailure;"function"==typeof b?b(a)||c():c()},d=function(){for(;0<b.length;)c(b.shift())};(function(a){__awct=a;__awct.a="awct";__awct.b=["google"];__awct.isVendorTemplate=!0})(function(e){var f={google_conversion_id:e["26"],google_conversion_label:e["27"],google_conversion_value:e[""]||0,google_remarketing_only:!1,onload_callback:e["30"],
gtm_onFailure:e["31"]};e[""]&&(f.google_conversion_currency=e[""]);e[""]&&(f.google_conversion_order_id=e[""]);b.push(f);a||(a=!0,ea("//www.googleadservices.com/pagead/conversion_async.js",function(){d();b={push:c}},function(){d();a=!1}))})})();

var __c;__c=function(a){return a["29"]};__c.a="c";__c.b=["google"];__c.isVendorTemplate=!0;




var Va=this;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Wa=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Xa=function(a){if(null==a)return String(a);var b=Wa.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Za=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Ga=function(a){if(!a||"object"!=Xa(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Za(a,"constructor")&&!Za(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Za(a,b)},$a=function(a,b){var c=b||("array"==Xa(a)?[]:{}),d;for(d in a)if(Za(a,d)){var e=a[d];"array"==Xa(e)?("array"!=Xa(c[d])&&(c[d]=[]),c[d]=$a(e,c[d])):Ga(e)?(Ga(c[d])||(c[d]={}),c[d]=$a(e,c[d])):c[d]=e}return c};var La=null,ab=Math.random(),bb=null,cb=null,Sa=!1,db={},eb={},Ta={};var fb,gb,hb,ib,jb,kb,lb,mb,nb,ob,pb,qb,S,sb,ub,vb,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb,Ib,Jb,Lb,Mb,Nb,Ob,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,U,ad,bd,cd,dd,ed,fd,gd,hd,id,jd,kd,ld,od,pd,qd,rd,sd,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,
ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf;
(function(){var a=function(a){return{toString:function(){return a}}};fb=a("");gb=a("0");hb="";ib=a("");jb=a("");kb=a("");lb=a("");mb=a("");nb=a("");ob=a("");pb=a("");qb=a("2");S=a("3");sb=a("");ub=a("");vb=a("");
wb=a("");xb=a("");yb=a("");zb=a("");Ab=a("");Bb=a("");Cb=a("");Db=a("");Eb=a("");Fb=a("");Gb=a("");Hb=a("");Ib=a("");Jb=a("");
Lb=a("");Mb=a("");Nb=a("");Ob=a("");Qb=a("");Rb=a("");Sb=a("4");Tb=a("");Ub=a("");Vb=a("");Wb=a("");Xb=a("");Yb=a("");Zb=a("");$b=a("");ac=a("");bc=a("");
cc=a("");dc=a("");ec=a("");fc=a("");gc=a("");hc=a("");ic=a("5");jc=a("");kc=a("6");lc=a("");mc=a("");nc=a("7");oc=a("");pc=a("");qc=a("8");rc=a("");sc=a("");
tc=a("");uc=a("9");wc=a("");xc=a("10");yc=a("");zc=a("11");Ac=a("");Bc=a("");Cc=a("");Dc=a("");Ec=a("");Fc=a("");Gc=a("12");Hc=a("");Ic=a("");Jc=a("");
Kc=a("");Lc=a("");Mc=a("");Nc=a("");Oc=a("");Pc=a("");Qc=a("");Rc=a("13");Sc=a("");Tc=a("");Uc=a("14");Vc=a("");Wc=a("30");Xc=a("31");Yc=a("");Zc=a("");$c=a("");
U=a("");ad=a("");bd=a("");cd=a("");dd=a("15");ed=a("16");fd=a("17");gd=a("");hd=a("");id=a("");jd=a("");kd=a("");ld=a("");od=a("");pd=a("");qd=a("");rd=a("18");sd=a("");vd=a("");wd=
a("");xd=a("");yd=a("");zd=a("19");Ad=a("");Bd=a("");Cd=a("");Dd=a("");Ed=a("20");Fd=a("");Gd=a("");Hd=a("");Id=a("");Jd=a("");Kd=a("");Ld=a("");Md=a("");Nd=a("");Od=a("");Pd=a("");
Qd=a("");Rd=a("");Sd=a("");Td=a("");Ud=a("");Vd=a("");Wd=a("");Xd=a("");Yd=a("");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");ee=a("");fe=a("");ge=a("");he=a("");
ie=a("");je=a("");ke=a("");le=a("");me=a("");ne=a("");oe=a("");pe=a("");qe=a("");re=a("");se=a("");te=a("");ue=a("");ve=a("");we=a("22");xe=
a("");ye=a("");ze=a("");Ae=a("");Be=a("");Ce=a("");De=a("");Ee=a("");Fe=a("");Ge=a("");He=a("");Ie=a("");Je=a("");Ke=a("");Le=a("");Me=a("");Ne=a("");
Oe=a("");Pe=a("");Qe=a("");Re=a("");Se=a("");Te="";Ue=a("");Ve=a("");We=a("");Xe=a("");Ye=a("");Ze=a("23");$e=a("");af=a("");bf=a("");cf=a("");df=a("");ef=
a("24");ff=a("");gf=a("");hf=a("");jf=a("")})();var kf=function(){},O=function(a){return"function"==typeof a},xa=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},lf=function(a){return"number"==Xa(a)&&!isNaN(a)},mf=function(a){return/^[0-9]+$/.test(a)},nf=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},of=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},K=function(a){return Math.round(Number(a))||0},Da=function(a){return"false"==
String(a).toLowerCase()?!1:!!a},pf=function(a){var b=[];if(xa(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},H=function(){return new Date},qf=function(a,b){if(!lf(a)||!lf(b)||a>b)a=0,b=2147483647;return Math.round(Math.random()*(b-a)+a)},rf=function(){this.prefix="gtm.";this.values={}};rf.prototype.set=function(a,b){this.values[this.prefix+a]=b};rf.prototype.get=function(a){return this.values[this.prefix+a]};rf.prototype.contains=function(a){return void 0!==this.get(a)};
var sf=function(a,b,c){try{if(!a[yd])return a[Uc](a,b||kf,c||kf);c&&c()}catch(d){}return!1},tf=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=of(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},Af=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},Bf=function(a){return function(){return a("GTM-MVMGKF")}},Cf=function(a){for(var b=0;b<a.length;b++)a[b]()},Df=H().getTime(),Fa=function(){return"gtm"+
Df++},Ha=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Ef=function(a){return null!==a&&void 0!==a&&void 0!==a.length},Ff=function(a,b){0==b?a.Wa=!0:a.complete=!0;var c=a.g;a.s&&(a.s.Ha[c]=b);db[c]&&(db[c].state=b)},Gf=function(a,b){a.sort(function(a,d){return b(a,d)?-1:b(d,a)?1:0})};var w=window,J=document,Jf=navigator,Q=function(a,b){var c=w[a];w[a]=void 0===c?b:c;return w[a]},I=function(a,b,c,d){return(d||"http:"!=w.location.protocol?a:b)+c},Kf=function(a){var b=J.getElementsByTagName("script")[0]||J.body||J.head;b.parentNode.insertBefore(a,b)},Ka=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},r=function(a,b,c){var d=J.createElement("script");d.type="text/javascript";d.async=
!0;d.src=a;Ka(d,b);c&&(d.onerror=c);Kf(d);return d},ga=function(a,b){var c=J.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";Kf(c);Ka(c,b);void 0!==a&&(c.src=a);return c},G=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},L=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},y=function(a){w.setTimeout(a,0)},Na=!1,
Oa=[],Lf=function(a){if(!Na){var b=J.createEventObject,c="complete"==J.readyState,d="interactive"==J.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){Na=!0;for(var e=0;e<Oa.length;e++)Oa[e]()}Oa.push=function(){for(var a=0;a<arguments.length;a++)y(arguments[a]);return 0}}},Mf=0,Nf=function(){if(!Na&&140>Mf){Mf++;try{J.documentElement.doScroll("left"),Lf()}catch(a){w.setTimeout(Nf,50)}}},za=function(a){var b=J.getElementById(a);if(b&&sa(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(sa(document.all[a][c],
"id")==a)return document.all[a][c];return b},sa=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},va=function(a){return a.target||a.srcElement||{}},Ra=function(a){var b=J.createElement("div");b.innerHTML="A<div>"+a+"</div>";for(var b=b.lastChild,c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},wa=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;for(var e=a,d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&
(e=null);return e},Of=!1,Pf=[],Qf=function(){if(!Of){Of=!0;for(var a=0;a<Pf.length;a++)Pf[a]()}},Rf=function(a){a=a||w;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},Pa=function(a){window.console&&window.console.log&&window.console.log(a)};var aa=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||w.location.protocol.replace(":","")).toLowerCase();switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||w.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:w.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=f.split("/");0<=nf(d||[],k[k.length-
1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");if(e)a:{for(var l=f.split("&"),m=0;m<l.length;m++){var p=l[m].split("=");if(decodeURIComponent(p[0]).replace(/\+/g," ")==e){f=decodeURIComponent(p.slice(1).join("=")).replace(/\+/g," ");break a}}f=void 0}break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},Sf=function(a){var b="";a&&a.href&&(b=a.hash?a.href.replace(a.hash,""):a.href);return b},ba=function(a){var b=J.createElement("a");
a&&(b.href=a);return b};var ia=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var fa=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=aa(ba(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1},Ca=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null};var Tf=new rf,Uf={},Wf={set:function(a,b){$a(Vf(a,b),Uf)},get:function(a){return P(a,2)},reset:function(){Tf=new rf;Uf={}}},P=function(a,b){if(2==b){for(var c=Uf,d=a.split("."),e=0;e<d.length;e++){if(void 0===c[d[e]])return;c=c[d[e]]}return c}return Tf.get(a)},Vf=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var Xf=Math.random(),Yf="1.000000">Xf;var Zf=kf;var $f=kf,ag=[],bg=!1,ca=function(a){return w["gtmDataLayer"].push(a)},cg=function(a){var b=!1;return function(){!b&&O(a)&&y(Bf(a));b=!0}},ig=function(){for(var a=!1;!bg&&0<ag.length;){bg=!0;var b=ag.shift();if(O(b))try{b.call(Wf)}catch(ya){}else if(xa(b))a:{var c=b;if("string"==Xa(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=Uf,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(ya){}}}else{var k=b,l=void 0;for(l in k)if(k.hasOwnProperty(l)){var m=l,
p=k[l];Tf.set(m,p);$a(Vf(m,p),Uf)}var q=!1,t=k.event,x=void 0;if(t){x=Df++;cb=t;if(!k["gtm.uniqueEventId"]){var u=x;Tf.set("gtm.uniqueEventId",u);$a(Vf("gtm.uniqueEventId",u),Uf)}var z=cg(k.eventCallback),E=k.eventTimeout;E&&w.setTimeout(z,Number(E));q=$f(x,t,z,k.eventReporter)}bb||(bb=k["gtm.start"])&&Zf();var D=k,C=x,A=t,M=Uf;if(!q){var F=x,N=t;
}cb=null;a=q||a}var T=b,R=Uf;hg();bg=!1}return!a},jg=function(){var a=ig();try{var b=w["gtmDataLayer"].hide;if(b&&void 0!==b["GTM-MVMGKF"]&&b.end){b["GTM-MVMGKF"]=!1;var c=!0,d;for(d in b)if(!0===b[d]){c=!1;break}c&&(b.end(),
b.end=null)}}catch(e){}return a};var ua=function(a,b,c){L(a,b,c,void 0)},ea=function(a,b,c){r(a,b,c)},Ua=function(a,b){w[a]=b},n=function(a,b,c){var d=w;b&&(void 0===d[a]||c&&!d[a])&&(d[a]=b);return d[a]},v=function(a,b,c){return("https:"==w.location.protocol?a:b)+c};var kg=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),lg={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},mg={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},ng=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},og=function(){var a=P("gtm.whitelist");
var b=a&&ng(pf(a),lg),c=P("gtm.blacklist")||P("tagTypeBlacklist")||[];kg.test(w.location&&w.location.hostname)&&(c=pf(c),c.push("nonGooglePixels","nonGoogleScripts"));var d=c&&ng(pf(c),mg),e={};return function(f){var g=f&&f[Uc];if(!g)return!0;if(void 0!==e[g.a])return e[g.a];var h=!0;if(a)a:{if(0>nf(b,g.a))if(g.b&&0<g.b.length)for(var k=0;k<g.b.length;k++){if(0>nf(b,
g.b[k])){h=!1;break a}}else{h=!1;break a}h=!0}var l=!1;if(c){var m;if(!(m=0<=nf(d,g.a)))a:{for(var p=g.b||[],q=new rf,t=0;t<d.length;t++)q.set(d[t],!0);for(t=0;t<p.length;t++)if(q.get(p[t])){m=!0;break a}m=!1}l=m}return e[g.a]=!h||l}};var _c=function(a){return a[ef]};_c.a="c";_c.b=["google"];var _ctv=function(){return"5"};_ctv.a="ctv";_ctv.b=["google"];var Hf=function(a){var b=J;return pg?b.querySelectorAll(a):null},qg=!1;if(J.querySelectorAll)try{var rg=J.querySelectorAll(":root");rg&&1==rg.length&&rg[0]==J.documentElement&&(qg=!0)}catch(a){}var pg=qg;var _eu=function(a){var b=String(P("gtm.elementUrl")||a[qc]||""),c=ba(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return cb};_e.a="e";_e.b=["google"];var wg=/(^|\.)doubleclick\.net$/i,xg=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Ea=function(a){for(var b=String(J.cookie).split(";"),c=[],d=0;d<b.length;d++){var e=b[d].split("="),f=of(e[0]);if(f&&f==a){var g=of(e.slice(1).join("="));g&&(g=decodeURIComponent(g));c.push(g)}}return c},yg=function(a,b,c,d,e){if(wg.test(J.location.hostname)||"/"==c&&xg.test(d))return!1;var f=a+"="+b+"; ";c&&(f+="path="+c+"; ");e&&(f+="expires="+e.toGMTString()+"; ");d&&(f+="domain="+d+";");var g=J.cookie;J.cookie=f;return g!=
J.cookie||0<=nf(Ea(a),b)},zg=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},Ag=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},Bg=function(){var a=aa(w.location,"host",!0).split(".");if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var Cg=function(a,b){this.f=a;this.j=b};Cg.prototype.toString=function(){var a=""+this.f;1<this.j&&(a=a+"-"+this.j);return a};var Dg=function(a,b){this.Fa=a;this.ka=b};Dg.prototype.toString=function(){return""+this.ka+"."+this.Fa};var Gg=function(a,b){var c=new Eg(null,a,b);Fg(c);return c},Eg=function(a,b,c){this.Oa=Math.floor(H().getTime()/864E5);this.ja=b||"auto";this.aa=c||"/";var d=zg(this.ja),e=Ag(this.aa);this.F=a||new Cg(d,e);this.h=[];this.C=new rf},Ig=function(a,b,c){b&&(""==c.Fa?Hg(a,b):(a.C.contains(b)||a.h.push(b),a.C.set(b,c)))},Jg=function(a,b){for(var c=0;c<b.length;c++)Ig(a,b[c][0],b[c][1])},Hg=function(a,b){var c=nf(a.h,b);0<=c&&a.h.splice(c,1);a.C.set(b,void 0)},Kg=function(a){for(var b=[],c=0;c<a.h.length;c++){var d=
a.h[c];b.push([d,a.C.get(d)])}return b},Lg=function(a){for(var b=0,c=0;c<a.h.length;c++)b=Math.max(b,a.C.get(a.h[c]).ka);return 864E5*b};Eg.prototype.toString=function(){if(0==this.h.length)return"";for(var a=[],b=0;b<this.h.length;b++){var c=this.h[b];a.push(""+c+"."+this.C.get(c).toString())}return"GAX1."+this.F.toString()+"."+a.join("!")};
var Mg=function(a,b){for(var c=new Date,d=Ag(a.aa),e=[],f=0;f<a.h.length;f++){var g=a.h[f];a.C.get(g).ka<a.Oa&&e.push(g)}for(f=0;f<e.length;f++)Hg(a,e[f]);if(a.h.length>(b||10))return!1;c.setTime(Lg(a));if("auto"!=a.ja)return yg("_gaexp",a.toString(),a.aa,a.ja,c);for(var h=Bg(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.F=new Cg(zg(h[k]),d),yg("_gaexp",a.toString(),a.aa,h[k],c)))return!0;return!1},Fg=function(a){for(var b=a.F.f,c=a.F.j,d=Ea("_gaexp"),e=[],f=0;f<d.length;f++){var g=Ng(a,d[f]);g&&e.push(g)}Gf(e,
function(a,d){var e=a.F,f=d.F;return e.f==f.f&&e.j==f.j?!1:e.f==b&&e.j==c?!0:f.f==b&&f.j==c?!1:e.f==b?f.f!=b||e.j<f.j:f.f==b?!1:e.j==c?f.f!=b&&(f.j!=c||e.f<f.f):f.j==c?!1:e.f<f.f||e.f==f.f&&e.j<f.j});a.F=0<e.length?e[0].F:new Cg(b,c);for(f=e.length-1;0<=f;f--)Jg(a,Kg(e[f]))},Ng=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=of(e[0]);if(0!=f.length){var g=2==e.length?of(e[1]):"1";if(mf(f)&&mf(g)){d=new Cg(K(f),K(g));
break a}}}d=void 0}if(d){for(var h=new Eg(d,a.ja,a.aa),k=(c[2]||"").split("!"),l=0;l<k.length;l++){var m=k[l].split(".");if(3==m.length){if(!mf(m[1]))return;Ig(h,m[0],new Dg(m[2],K(m[1])))}}return h}}};var _v=function(a){var b=P(a[Ed].replace(/\\\./g,"."),a[ic]);return void 0!==b?b:a[qc]};_v.a="v";_v.b=["google"];var _f=function(a){var b=String(P("gtm.referrer")||J.referrer);if(!b)return b;var c=ba(b);return b};_f.a="f";_f.b=["google"];var _smm=function(a){var b=a[dd],c=a[zd]||{};return c.hasOwnProperty(b)?c[b]:a[qc]};_smm.a="smm";_smm.b=["google"];var Ba=function(a){var b=w.location,c;(c=a[fc]?a[fc]:P("gtm.url"))&&(b=ba(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[Sb]&&(f=aa(b,a[Sb],a[qe],a[pc],a[de]));return f},_u=Ba;_u.a="u";_u.b=["google"];var _cn=function(a){return 0<=String(a[qb]).indexOf(String(a[S]))};_cn.a="cn";_cn.b=["google"];var _eq=function(a){return String(a[qb])==String(a[S])};_eq.a="eq";_eq.b=["google"];var Og=new String("undefined"),ah=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===Og?b:a[d]);return c.join("")}};ah.prototype.toString=function(){return this.resolve("undefined")};ah.prototype.valueOf=ah.prototype.toString;var bh={},ch=function(a,b){var c=Df++;bh[c]=[a,b];return c},dh=function(a){var b=a?0:1;return function(a){var c=bh[a];if(c&&O(c[b]))c[b]();bh[a]=void 0}};var eh=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},fh=function(a,b){return a<b?-1:a>b?1:0};var gh;a:{var hh=Va.navigator;if(hh){var ih=hh.userAgent;if(ih){gh=ih;break a}}gh=""}var W=function(a){return-1!=gh.indexOf(a)};var jh=function(){W("iPod")},kh=function(){return W("iPhone")&&!W("iPod")&&!W("iPad")};var lh=function(a){lh[" "](a);return a};lh[" "]=function(){};var nh=function(a,b){var c=mh;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var oh=W("Opera"),ph=W("Trident")||W("MSIE"),qh=W("Edge"),rh;if(rh=W("Gecko"))rh=!(-1!=gh.toLowerCase().indexOf("webkit")&&!W("Edge"));var sh=rh&&!(W("Trident")||W("MSIE"))&&!W("Edge"),th=-1!=gh.toLowerCase().indexOf("webkit")&&!W("Edge");th&&W("Mobile");W("Macintosh");W("Windows");W("Linux")||W("CrOS");var uh=Va.navigator||null;uh&&(uh.appVersion||"").indexOf("X11");W("Android");kh();W("iPad");jh();kh()||W("iPad")||jh();var vh=function(){var a=Va.document;return a?a.documentMode:void 0},wh;
a:{var xh="",yh=function(){var a=gh;if(sh)return/rv\:([^\);]+)(\)|;)/.exec(a);if(qh)return/Edge\/([\d\.]+)/.exec(a);if(ph)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(th)return/WebKit\/(\S+)/.exec(a);if(oh)return/(?:Version)[ \/]?(\S+)/.exec(a)}();yh&&(xh=yh?yh[1]:"");if(ph){var zh=vh();if(null!=zh&&zh>parseFloat(xh)){wh=String(zh);break a}}wh=xh}
var Ah=wh,mh={},Bh=function(a){return nh(a,function(){for(var b=0,c=eh(String(Ah)).split("."),d=eh(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{var k=/(\d*)(\D*)(.*)/.exec(g)||["","","",""],l=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==l[0].length)break;b=fh(0==k[1].length?0:parseInt(k[1],10),0==l[1].length?0:parseInt(l[1],10))||fh(0==k[2].length,0==l[2].length)||fh(k[2],l[2]);g=k[3];h=l[3]}while(0==b)}return 0<=b})},Ch;
var Dh=Va.document;Ch=Dh&&ph?vh()||("CSS1Compat"==Dh.compatMode?parseInt(Ah,10):5):void 0;var Eh;if(!(Eh=!sh&&!ph)){var Fh;if(Fh=ph)Fh=9<=Number(Ch);Eh=Fh}Eh||sh&&Bh("1.9.1");ph&&Bh("9");var Qa=function(a,b){var c="";ph&&!Gh(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(Hh)a.srcdoc=d;else if(Ih){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else Jh(a,d)},Hh=th&&"srcdoc"in document.createElement("iframe"),Ih=sh||th||ph&&Bh(11),Jh=function(a,b){ph&&Bh(7)&&!Bh(10)&&6>Kh()&&Lh(b)&&(b=Mh(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};ph&&!Gh(a)?Nh(a,c):c()},Kh=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},Gh=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{lh(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},Oh=0,Nh=function(a,b){var c="goog_rendering_callback"+Oh++;window[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},Lh=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},Mh=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var di=function(a,b,c,d){var e=b+": "+c+(d?" !important":""),f=document;if(f.createStyleSheet){var g=ai(f),h=g.rules.length;g.addRule(a,e);return function(){g.removeRule?g.removeRule(h):g.deleteRule(h);g.addRule("x","-",h)}}var k=bi(a+"{"+e+"}",f);ci(k,f);var l=k.parentNode;return function(){l.removeChild(k)}},ei=null,ai=function(a){if(ei)return ei;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return ei=c}0==a.styleSheets.length&&
a.createStyleSheet();return ei=a.styleSheets[0]},bi=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},ci=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var li={},mi=void 0,ni=function(a){var b=li[a];b||(b={id:a,v:[],W:0,Ia:null,za:void 0,Da:!1},li[a]=b);mi=b},pi=function(a,b,c,d){var e=mi;if(!pg||!e)return!1;var f={id:e.id+":"+e.v.length,eb:b,U:[],Za:c,G:a,ua:0,sa:d||null,Na:0,V:!1};e.v.push(f);null===a?(f.V=!0,b(null)):oi(e);return!0},qi=function(a){var b=di(a,"visibility","hidden",!0);return function(){O(b)&&b.apply();b=null}},ri=function(a,b,c,d){var e=b;if(!Na){var f=qi(a.A);Oa.push(f);e=function(a,c){var d=b(a,c);f();return d}}return pi(a,e,
c,d)},oi=function(a){if(!a.Da){for(var b=a.W;b<a.v.length;b++){var c=a.v[b],d=b==a.W;if(!c.V&&!si(d,c))break;c.V&&d&&a.W++}a.v.length>a.W?(a.Ia||(a.Ia=w.setTimeout(function(){a.Ia=null;oi(a)},80)),Na||a.za||(a.za=function(){y(function(){oi(a)})},L(J,"DOMContentLoaded",a.za))):ti(a)}},ti=function(a){for(var b=0;b<a.v.length;b++){var c=a.v[b];if(c.G)for(var d=Hf(c.G.A)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(ui(f,c.id),c.U.push(vi(f,c.id)))}}},si=
function(a,b){var c=[];if(b.G){var d=wi(b.G,b.id),e=null;b.sa&&(e=wi(b.sa,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!Na&&(null===b.sa.o||b.Na+c.length<b.sa.o)))break;c.push({element:g,Hb:h})}}if(!Na&&b.Za&&(!a||null==b.G.o||b.G.o!=b.ua+c.length))return!1;for(var k=0;k<c.length;k++){var l=c[k].element,m=c[k].Hb,p;b.ua++;ui(l,b.id);m&&(b.Na++,p=b.id+"-t",ui(m,p));var q=b.eb(l,m);O(q)&&b.U.push(q);b.U.push(vi(l,b.id));m&&p&&b.U.push(vi(m,p))}if(b.G.o&&
b.G.o==b.ua||Na)b.V=!0;return!0},ui=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},vi=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},wi=function(a,b){for(var c=Hf(a.A)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.D&&!xi(f))break;d.push(f)}}return d},xi=function(a){if(Na)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var ja,yi,zi,ra=/(Firefox\D28\D)/g.test(Jf.userAgent),Bi=function(a,b){return function(c){c=c||w.event;var d=va(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=wa(d,["a","area"]),e=!d||!d.href||Ai(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?ja:zi;if(c.defaultPrevented||!1===c.returnValue||c.X&&c.X()){if(d){var g={simulateDefault:!1},h=la(f,["wnc","nwnc"]);h&&na(a,d,g,f.wt,h)}}else{if(d){var g={},k,l=la(f,["wnc",
"nwnc","nwc","wc"]);(k=na(a,d,g,f.wt,l))||(oa(g.eventReport,f)?b=!0:e=!0);e=e||k||"LINK_CLICK"==a&&ra;g.simulateDefault=!k&&b&&!e;g.simulateDefault&&(e=ta(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=k||!b||e;return c.returnValue}return!0}}}},na=function(a,b,c,d,e){var f=d||2E3,g={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||sa(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event="gtm.linkClick";
g["gtm.elementUrl"]=b.href;g.eventTimeout=f;g.eventCallback=Ci(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=e||"";g.event="gtm.formSubmit";g["gtm.elementUrl"]=Di(b);g.eventTimeout=f;g.eventCallback=Ei(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";g["gtm.elementUrl"]=(b.attributes&&b.attributes.formaction?b.formAction:"")||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return ca(g)},Di=
function(a){var b=a.action;b&&b.tagName&&(b=a.cloneNode(!1).action);return b},qa=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},ta=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(Jf.userAgent),e=qa(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);b.targetWindow=w.frames&&w.frames[f]||w[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName=
"gtm_autoEvent_"+H().getTime(),b.targetWindow=w.open("",b.targetWindowName));break;default:d&&!w.frames[e]?(b.simulateDefault=!1,c=!0):(w.frames[e]||(b.targetWindowName=e),b.targetWindow=w.frames[e]||w.open("",e))}return c},Ci=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||H().getTime(),500>H().getTime()-c&&w.setTimeout(Ci(a,b,c),25)))}},Ei=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&
(d=a.target,a.target=b.targetWindowName);J.gtmSubmitFormNow=!0;pa(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||H().getTime(),500>H().getTime()-c&&w.setTimeout(Ei(a,b,c),25)}},la=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},Fi=function(a,b,c,d,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;f="0"}var g=a.wt;b&&(!g||g>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][f]=!0},oa=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;
for(var c=0;c<Gi.length;c++)if(a.passingRules[c]){var d=Hi[c],e=d&&d[0]&&d[0][0]||d[1]&&d[1][0];if(e&&"0"!=e&&(b.wc[e]||b.wnc[e]))for(var f=Gi[c][1],g=0;g<f.length;g++)if(a.resolvedTags[f[g]])return!0}return!1},Aa=function(a,b,c,d,e){var f,g,h=!1;switch(a){case "CLICK":if(J.gtmHasClickListenerTag)return;J.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=va(a);b&&na("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":b&&!yi&&(yi=Sf(J.location));Fi(zi,b||!1,c||!1,d,e);if(J.gtmHasLinkClickListenerTag)return;
J.gtmHasLinkClickListenerTag=!0;f="click";g=Bi(a,b||!1);break;case "FORM_SUBMIT":Fi(ja,b||!1,c||!1,d,e);if(J.gtmHasFormSubmitListenerTag)return;J.gtmHasFormSubmitListenerTag=!0;f="submit";g=Bi(a,b||!1);break;default:return}L(J,f,g,h)},Ai=function(a){if(!yi)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=ba(a);return yi==Sf(c)},pa=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;
J.gtmFormElementSubmitter||(J.gtmFormElementSubmitter=J.createElement("form"));return J.gtmFormElementSubmitter.submit.call?J.gtmFormElementSubmitter.submit:a.submit};var Ia=function(a,b){var c=b||Va,d=c.onerror,e=!1;th&&!Bh("535.3")&&(e=!e);c.onerror=function(b,c,h,k,l){d&&d(b,c,h,k,l);a({message:b,fileName:c,Sa:h,Xb:k,error:l});return e}};var Fj=92,Gj=[],Hj=[],Ij=[],Jj=new rf,Kj=[],Z=[],Gi=[],Hi=[],Lj=function(){this.L=[]};Lj.prototype.set=function(a,b){this.L.push([a,b]);return this};Lj.prototype.resolve=function(a,b){for(var c={},d=0;d<this.L.length;d++){var e=Mj(this.L[d][0],a,b),f=Mj(this.L[d][1],a,b);c[e]=f}return c};var Nj=function(a){this.index=a};Nj.prototype.resolve=function(a,b){var c=Ij[this.index];if(c&&!b(c)){var d=c[ed];if(a){if(a.get(d))return;a.set(d,!0)}c=Mj(c,a,b);a&&a.set(d,!1);return sf(c)}};
var _M=function(a){return new Nj(a)},Oj=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=Mj(Gj[a[f]],b,c);g===Og&&(e=!0);d.push(g)}return e?new ah(d):d.join("")}},_T=function(a){return new Oj(arguments)},Pj=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=
function(c,d){var e=Mj(a[0],c,d);if(a[0]instanceof Nj&&b(8)&&b(16)){if(e===Og)return e;var f=Fa();Jj.set(f,e);return'google_tag_manager["GTM-MVMGKF"].macro(\''+f+"')"}for(var e=String(e),g=1;g<a.length;g++)e=Y[a[g]](e);return e}},_E=function(a,b){return new Pj(arguments)},Qj=function(a,b){this.w=a;this.ra=b},_R=function(a,b){return new Qj(a,b)},Mj=function(a,b,c){var d=a;if(a instanceof Nj||a instanceof Lj||a instanceof Oj||a instanceof Pj)return a.resolve(b,c);if(!(a instanceof Qj))if(xa(a))for(var d=
[],e=0;e<a.length;e++)d[e]=Mj(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=Mj(a[f],b,c))}return d},Rj=function(a,b){var c=b[a],d=c;if(c instanceof Nj||c instanceof Pj||c instanceof Oj||c instanceof Qj)d=c;else if(xa(c))for(var d=[],e=0;e<c.length;e++)d[e]=Rj(c[e],b);else if("object"==typeof c){var d=new Lj,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],Rj(c[f],b))}return d},Tj=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");
0==a&&(e[1]=Gj[e[1]]);if(1==a)for(var f=Sj(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=Hj[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=Sj(e[g]);3==a&&(c[d]=Gj[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=Gj[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},Sj=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<Fj;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:
62;1&f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},Uj=function(a,b,c){a.push.apply(a,Tj(b,c))};
var eg=function(){},ck=function(a){},hg=function(){},dk=function(a){},ek=function(a,b){},fk=function(a,b){},fg=function(a){};var gk,hk;var rk=function(a){return function(){}},sk=function(a){return function(){}};var tk=function(a){var b=this;this.g=a;this.complete=this.Wa=!1;this.qa=[];this.la=[];this.S=function(){if(b.s&&b.s.event){var c=b.s.event,d=b.g;}b.complete||Cf(b.qa);Ff(b,1);if(eb[a])for(var e=0;e<eb[a].length;e++)eb[a].shift().S()};this.R=function(){if(b.s&&b.s.event){var c=b.s.event,d=b.g;}b.complete||
Cf(b.la);Ff(b,2);if(eb[a])for(var e=0;e<eb[a].length;e++)eb[a].shift().R()};this.B=kf},uk=function(a,b){a.qa.push(b)},vk=function(a,b){a.la.push(b)},wk=function(a){this.M=[];this.Ga=[];this.Pa={};this.ya=[];this.Y=0;this.Va={};this.Xa={};this.Ha={};this.event=a};wk.prototype.addListener=function(a){this.ya.push(a)};
var xk=function(a,b,c,d,e,f){if(!c.complete){a.M[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=xa(d)?d.slice():["or",d];e=xa(e)?e.slice():[e];f=xa(f)?f.slice():[f];a.Pa[b]=d;a.Va[b]=0<e.length;a.Xa[b]=0<f.length;a.Y++;var g=function(){0<a.Y&&a.Y--;0<a.Y||Cf(a.ya)};uk(c,g);vk(c,g)}},yk=function(a,b,c){a.M[b]&&(uk(a.M[b],function(){c(b,!0)}),vk(a.M[b],function(){c(b,!1)}))},zk=function(a,b){var c=!1;return function(d,e){var f;a:{for(var g=0;g<a.length;g++)if(a[g]instanceof Qj&&a[g].w===
d||a[g]===d){f=g;break a}f=-1}c||0>f||("or"==a[0]?e?(c=!0,b()):(a.splice(f,1),1==a.length&&(c=!0)):e?(a.splice(f,1),1==a.length&&(c=!0,b())):c=!0)}},Dk=function(a,b){var c=[],d=!1,e=function(b){var f,g,h=Z[b];if(a.event.c(h)){}else g=Ak(h,b,a);if(f=g){var k=Bk(b,!0);0<k.length&&e(k[0].w);c.push(f);var l=Bk(b,!1);0<l.length&&e(l[0].w)}else d=
!0};e(b);if(!d){for(var f=0;f<c.length;f++){var g=c[f],h=Bk(g.g,!0);if(0<h.length){var k=c[f-1],l=Ck(g);uk(k,l);0==h[0].ra&&vk(k,l)}var m=Bk(g.g,!1);0<m.length&&(l=Ck(c[f+1]),uk(g,l),0==m[0].ra&&vk(g,l))}a.Ga.push(c)}},Bk=function(a,b){var c=b?ne:Ee,d=Z[a],e=void 0===d[c]?[]:d[c];return xa(e)?e:[e]},Ck=function(a){return function(){a.B()}},Fk=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Bk(a,!0);0<b.length&&f(b[0].w);e.push(a);var c=Bk(a,!1);0<c.length&&f(c[0].w)};
f(d.g);b[d.g]=e}Ek(a,b);return b},Ek=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].g,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<nf(b[e],d)){delete b[d];break}}};var Hk=function(a,b){return function(){a[Wc]=b.S;a[Xc]=b.R;var c=b.g,d=b.s&&b.s.Ha[c],e=db[c]&&db[c].state,f=d?void 0!==d:b.Wa||b.Yb,g=db[c]&&db[c].firingOption,h=g&&2==g,k=g&&1==g;if(!f&&void 0===e||!f&&!h||!h&&!k){Ff(b,0);var l=b.s?b.s.event:void 0;a=Gk(a,l?l.c:og());if(l){var m=a;ek(l,c)}sf(a,b.S,b.R)}else h&&0==e||k&&0==d?eb[c].push(b):h&&1==e||k&&1==d?b.S():b.R()}},Gk=function(a,b){a=Mj(a,new rf,b);return a},Ak=function(a,b,c){var d=new tk(b);d.s=c;uk(d,rk(a));vk(d,sk(a));d.B=Hk(a,d);return d};
var Lk=!1,_ua=function(a,b,c){function d(a){var b=[].slice.call(arguments,0);b[0]=p+b[0];w[l()].apply(window,b)}function e(b,c){void 0!==a[c]&&d("set",b,a[c])}function f(a,b){return void 0===b?b:a(b)}function g(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&d("set",a+c,b[c])}function h(){var b=function(a,b,c){if(!Ga(b))return!1;for(var e=Ha(Object(b),c,[]),f=0;e&&f<e.length;f++)d(a,e[f]);return!!e&&0<e.length},c;a[zc]?c=P("ecommerce"):
a[yc]&&(c=a[yc].ecommerce);if(!Ga(c))return;c=Object(c);var e=Ha(a[Rc],"currencyCode",c.currencyCode);void 0!==e&&d("set","&cu",e);b("ec:addImpression",c,"impressions");if(b("ec:addPromo",c[c.promoClick?"promoClick":"promoView"],"promotions")&&c.promoClick){d("ec:setAction","promo_click",c.promoClick.actionField);return}for(var f="detail checkout checkout_option click add remove purchase refund".split(" "),g=0;g<f.length;g++){var h=c[f[g]];if(h){b("ec:addProduct",h,"products");d("ec:setAction",f[g],
h.actionField);break}}}function k(a,b,c){var d=0;if(void 0!==a)for(var e in a)if(a.hasOwnProperty(e)&&(c&&x[e]||!c&&void 0===x[e])){var f=u[e]?Da(a[e]):a[e];"anonymizeIp"!=e||f||(f=void 0);b[e]=f;d++}return d}Q("GoogleAnalyticsObject",a[Ed]||"ga");var l=function(){return w.GoogleAnalyticsObject},m=Q(l(),function(){var a=w[l()];a.q=a.q||[];a.q.push(arguments)});m.l=Number(H());var p="",q="";"string"!=typeof a[Re]?(q=Fa(),p=q+"."):""!==a[Re]&&
(q=a[Re],p=q+".");var t=!1;var x={name:!0,clientId:!0,sampleRate:!0,siteSpeedSampleRate:!0,alwaysSendReferrer:!0,allowAnchor:!0,allowLinker:!0,cookieName:!0,cookieDomain:!0,cookieExpires:!0,cookiePath:!0,legacyCookieDomain:!0,legacyHistoryImport:!0,storage:!0},u={allowAnchor:!0,allowLinker:!0,alwaysSendReferrer:!0,anonymizeIp:!0,exFatal:!0,forceSSL:!0,javaEnabled:!0,legacyHistoryImport:!0,nonInteraction:!0,useBeacon:!0};
var z={name:q};k(a[Rc],z,!0);m("create",a[gb],z);d("set","&gtm","GTM-MVMGKF");g("dimension",a[uc]);
var E={};k(a[Rc],E,!1)&&d("set",E);var D;a[rd]&&d("require","linkid","linkid.js");d("set","hitCallback",function(){if(O(a[Yc]))a[Yc]();else{var c=a[Rc],d=c&&c.hitCallback;O(d)&&d()}b()});if(a[Ne]){}else if(a[Oe]){}else if(a[Qe]){}else if(a[Pe]){}else if(a[oc]){}else if(a[mc]){}else if(a[Me]){}else{a[Gc]&&(d("require","ec","ec.js"),h());if(a[xc]&&!a[Ic]){var R="_dc_gtm_"+String(a[gb]).replace(/[^A-Za-z0-9-]/g,"");d("require","displayfeatures",void 0,{cookieName:R})}D?d("send","pageview",D):d("send","pageview");}if(!Lk){var V=a[kc]?"u/analytics_debug.js":"analytics.js";a[fd]&&!a[kc]&&(V="internal/"+V);
Lk=!0;r(I("https:","http:","//www.google-analytics.com/"+V,t),function(){w[l()].loaded||c()},c)}};_ua.a="ua";_ua.b=["google"];var Mk=!1;var Nk=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=Kj[b]&&Mj(Kj[b],new rf,c),e=d;if(d)if(d[pb]&&xa(d[S]))for(var f=d[S],e=!1,g=0;!e&&g<f.length;g++)d[S]=f[g],e=sf(d);else e=sf(d);a[b]=[e,d]}return a[b]}},bk=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.P(c[d],a.c)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.P(e[d],a.c)[0])return!1;return!0},Ok=!1,$f=function(a,b,c,d){switch(b){case "gtm.js":if(Ok)return!1;Ok=!0;break;case "gtm.sync":if(P("gtm.snippet")!=ab)return!1}P("tagTypeBlacklist");
for(var e={id:a,name:b,ha:c||kf,fa:Sj(),pa:Sj(),P:Nk(),c:og()},f=[],g=0;g<Gi.length;g++)if(bk(e,Gi[g])){f[g]=!0;for(var h=e,k=Gi[g],l=k[1],m=0;m<l.length;m++)h.fa[l[m]]=!0;for(var p=k[3],m=0;m<p.length;m++)h.pa[p[m]]=!0}else f[g]=!1;ek(e);var t=[];for(var x=0;x<Fj;x++)if(e.fa[x]&&!e.pa[x])if(e.c(Z[x])){}else{t[x]=Z[x];}e.T=t;for(var u=new wk(e),z=0;z<Fj;z++)if(e.fa[z]&&!e.pa[z])if(e.c(Z[z])){}else{var E=e.T[z],D=Ak(E,z,u);xk(u,z,D,E[rc],E[ne],E[Ee]);if(E[fb])break}u.addListener(e.ha);for(var C=[],
A=0;A<u.M.length;A++){var M=u.M[A];if(M){var B=u.Pa[A],F=u.Va[A],N=u.Xa[A];if(0!=B.length||F||N){if(0<B.length)for(var T=zk(B,M.B),R=0;R<B.length;R++)B[R]instanceof Qj&&B[R].w!=A&&yk(u,B[R].w,T);(F||N)&&Dk(u,A)}else C.push(A)}}for(A=0;A<C.length;A++)u.M[C[A]].B();for(A=0;A<u.Ga.length;A++){for(var ya=u.Ga[A],V=ya,ka=[],ha=0;ha<V.length;ha++){var tb=V[ha],rb=tb.g,Pb=db[rb],td=Pb.firingOption;0!=td&&(1==td&&void 0!==tb.s.Ha[rb]||2==td&&void 0!==Pb.state)&&ka.push(tb)}var ud=Fk(ka),vc=void 0;for(vc in ud)if(ud.hasOwnProperty(vc)){for(var uf=
void 0,fj=void 0,md=ud[vc],bl=md[0],ij=md[md.length-1],jj,Ja=0;Ja<V.length;Ja++){var nd=V[Ja];!uf&&nd.g==bl&&0<Ja&&(uf=V[Ja-1]);nd.g==ij&&Ja<V.length-1&&(fj=V[Ja+1]);if(-1<nf(md,nd.g))if(jj=V.splice(Ja,1)[0],nd.g==ij)break;else Ja--}if(jj){var kj=Number(vc),ma=uf,vf=fj;if(ma){var cl=ma.qa[0],dl=ma.la[0],lj=ma;lj.qa=[];lj.la=[];uk(ma,cl);vk(ma,dl)}if(ma&&vf){var wf=Ck(vf);uk(ma,wf);var xf=Bk(ma.g,!1);0<xf.length&&xf[0].w!=kj&&0==xf[0].ra&&vk(ma,wf);var yf=Bk(vf.g,!0);0<yf.length&&yf[0].w!=kj&&0==yf[0].ra&&
vk(ma,wf)}}}0<ya.length&&ya[0].B()}0<u.Y||Cf(u.ya);d&&O(d)&&d({passingRules:f,resolvedTags:e.T});
if("gtm.js"==b||"gtm.sync"==b)a:{}for(var oj in e.T)if(e.T.hasOwnProperty(oj)){var pj=e.T[oj],zf;if(!(zf=void 0==pj[ed])){var qj=pj[ed];zf=!("function"!=typeof String.prototype.startsWith?0===qj.indexOf("_implicit"):qj.startsWith("_implicit"))}if(zf)return!0}return!1};var Pk={macro:function(a){if(Jj.contains(a))return Jj.get(a)}};Pk.dataLayer=Wf;Pk.onHtmlSuccess=dh(!0);Pk.onHtmlFailure=dh(!1);Pk.callback=function(a){Ta.hasOwnProperty(a)&&O(Ta[a])&&Ta[a]();delete Ta[a]};Pk.jb=function(){var a=w.google_tag_manager;a||(a=w.google_tag_manager={});a["GTM-MVMGKF"]||(a["GTM-MVMGKF"]=Pk);La=a};(function(){var a=function(a){var b=Q("google_tag_manager",{}),d=b[a];d||(d=b[a]={},d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};zi=a("linkClickMap");ja=a("formSubmitMap")})();
Gj.push.apply(Gj,function(){for(var a=[_eq,_e,'_event',_M(0),'concordEvent','2038726_4',_ua,true,__c,'property id - console','1','UA-36037335-1',_M(1),false,'14','19','20','15','17','16','31','Container ID and Version',_c,'Container ID','GTM-MVMGKF',_M(2),':',_ctv,'Container Version',_M(3),_T(25,26,29),_M(4),_v,'eventType',2,_M(5),'eventName',_M(6),'pageName',_M(7),'signedIn',_M(8),_smm,'internalUser Lookup','internalUser',_M(9),'true','True',{10:47,46:47,47:47},'',_M(10),'projectNumber','not set',_M(11),{14:31,15:35,16:37,17:39,18:41,19:50,20:53},'allowLinker','anonymizeIp','cookieDomain','legacyHistoryImport','page','title','false','auto','/virtual/','/',_T(63,35,64,37),'packageName\x3d','packageName',_M(12),'\x26','metadata',_M(13),_T(66,68,69,71),{55:46,56:61,57:62,58:61,59:65,60:72},'\x26tid','\x26cd14','\x26cd19','\x26cd20','\x26cd15','\x26cd17','\x26cd16','\x26cd31',{74:12,75:31,76:35,77:37,78:39,79:41,80:50,81:53,55:46,56:61,57:62,58:61,59:65,60:72},1,'connectApp','finish',_cn,'packageType\x3dios','2038726_5',__awct,'978586856','gUraCIH9hWcQ6JnQ0gM',_u,'_url',_M(14),'packageType\x3dandroid','2038726_6','mlEtCJOFgWcQ6JnQ0gM',3,'trackExperiment','2038726_8','configureExperiment','experimentID','experimentType',_M(15),'exp name goes here','exp id goes here',{105:106},_M(16),{14:31,15:101,16:108,17:39,18:41,19:50,20:53},'/virtual/configureExperiment/',_T(110,104),'expId\x3d',',expVar\x3d','experimentVariant','variant',_M(17),_T(112,108,113,116),{55:46,56:61,57:62,58:61,59:111,60:117},{74:12,75:31,76:101,77:108,78:39,79:41,80:50,81:53,55:46,56:61,57:62,58:61,59:111,60:117},4,'Page URL','Page Hostname','host','Page Path','path',_f,'Referrer','Event'],b=[],c=0;c<a.length;c++)b[c]=Rj(c,a);return b}());Uj(Hj,0,"14:0,14:1,16:2,2:3,3:4,14:6,21:7,14:8,16:9,25:10,29:11,0:12,12:13,11:13,16:21,14:22,16:23,24:24,14:27,16:28,29:30,14:32,16:33,20:33,5:34,16:36,20:36,16:38,20:38,16:40,20:40,14:42,16:43,16:44,20:44,15:45,19:48,8:49,16:51,20:51,8:52,9:54,23:13,16:67,20:67,16:70,20:70,13:73,6:13,17:7,7:13,1:82,18:13,10:13,22:83,2:35,3:84,2:37,3:85,14:86,2:71,3:87,14:89,26:90,27:91,14:92,16:93,28:94,22:34,3:95,27:97,22:98,3:99,16:102,16:103,20:103,15:104,19:107,9:109,16:114,20:115,13:118,1:119,22:120,16:121,16:122,4:123,16:124,4:125,14:126,16:127,16:128");Uj(Ij,1,"G,Ae,AA4,AAAD,AKEE,AAA4B,AAAIH,AAAIZ,AAAIhB,AAAIBY,AAAAAmD,AAAIBAc,AAAIBAAG,AAAIBAAY,AAAAAAAAAAgB,AAAIBAAAAAAAM,AAAAACCAAAAAy,AAAIBAAAAAAAAG,AAAAAAAAAAgAAAB,AAAAAAAAAAgAAAG,AAAAAAAAAAgAAAY,AAAAAAAAAAAAAAgB,CAAAAAAAAAAAAAAC");Uj(Kj,1,"Z,BAAAAAAAAG,BAAAAAAAAY,AAAAAAAAAgD,AAAAAAAAAgBI,JAAAAAAAAAAAB");Uj(Z,1,"ghDAAAgh_B,AJAAAAAAAAcG,AJAAAAAAAAMy,ghDAAAAB3AAAA5");Uj(Gi,2,"B:B::,P:C::,X:E::,g:I::");Uj(Hi,4,"5:,88:,96:,100:");for(var Qk=0;Qk<Z.length;Qk++){var Rk=Z[Qk],Sk=1;Rk[Ld]?Sk=2:Rk[We]&&(Sk=0);db[Qk]={firingOption:Sk,state:void 0};eb[Qk]=[]}Pk.jb();
(function(a){})("async");
(function(){var a=Q("gtmDataLayer",[]),b=Q("google_tag_manager",{}),b=b["gtmDataLayer"]=b["gtmDataLayer"]||{};Oa.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Pf.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(ag.push.apply(ag,b);300<this.length;)this.shift();return ig()};ag.push.apply(ag,a.slice(0));y(jg)})();var $k=w;
if("interactive"==J.readyState&&!J.createEventObject||"complete"==J.readyState)Lf();else{L(J,"DOMContentLoaded",Lf);L(J,"readystatechange",Lf);if(J.createEventObject&&J.documentElement.doScroll){var al=!0;try{al=!$k.frameElement}catch(a){}al&&Nf()}L($k,"load",Lf)}"complete"===J.readyState?Qf():L(w,"load",Qf);
(function(a){})("async");(function(){})();var _vs="res_ts:1476382725537000,srv_cl:137858665,ds:live,cv:5";
})()
